### ISSUE TITLE
gv dependency problems

### ISSUE THREAD

**Issue by pschloss** [arb-project/homebrew-arb#1]
I'm trying to install the development/production version as the stable version doesn't seem to exist on Mojave. When I do the following, I get errors...

```
$ brew install arb --devel
==> Installing arb from arb-project/arb
Error: No available formula with the name "gv" (dependency of arb-project/arb/arb)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
cgvg                        gvp                         igv                         libsigsegv
To install one of them, run (for example):
  brew install cgvg
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I ran the `git -C` command they suggest, but re running the `brew install` didn't change the result. I noticed that `gv` is not listed as a formula on the [homebrew site](https://formulae.brew.sh/formula/).

Any suggestions for a fix? Alternatively, how likely are you all to make Preview the default pdf viewer as stated in your README? Any time line?

**Comment by jgerken** [comment]
Hi Pat,

I did not notice before that homebrew has removed the `gv` formula from their repository. Fortunately, another user GitHub user stepped up to provide the `gv` formula. Please run the following commands to install ARB:

```
brew tap denismm/gv 
brew install arb --devel
```

I tried it on a Mac with Mojave installed on which ARB had never been installed. On that machine the install was successful. If `ghostscript` is already installed on your machine, the install might still fail. In that case you need to uninstall `ghostscript` first and then install `arb` (`ghostscript` would be re-installed in the process).

All the best,
Jan

**Comment by pschloss** [comment]
Awesome, that worked. Thanks for creating the `arb` formula!
