### ISSUE TITLE
Build broken on MacOS 12 (Monterey)

### ISSUE THREAD

**Issue by pranalideore1** [arb-project/homebrew-arb#15]
Encountered following error while installing production ARB on MacOS

[37:19.N] ------------------------------------------------ Checking NTREE.a
Target 'NTREE.a' not found
-> rebuilding NTREE.a (Wed Dec 31 23:59:59 1969)
ar -csq NTREE.a AP_consensus.o AP_pos_var_pars.o ColumnStat_2_gnuplot.o NT_branchAnalysis.o NT_cb.o NT_concatenate.o NT_dbrepair.o NT_edconf.o NT_extern.o NT_group_search.o NT_import.o NT_ins_col.o NT_join.o NT_main.o NT_shadeTree.o NT_sort.o NT_sync_scroll.o NT_syncroot.o NT_taxonomy.o NT_trackAliChanges.o NT_tree_cmp.o NT_userland_fixes.o NT_validManual.o NT_validNameParser.o NT_validNames.o ScrollSynchronizer.o ad_ext.o ad_spec.o ad_transpro.o ad_trees.o
[37:20.N] ------------------------------------------------ Make NTREE [done]
make[1]: *** [arb] Error 2
make: *** [all] Error 2

**Comment by jgerken** [comment]
Unfortunately, the last 15 lines of the log file which Home brew automatically prints to the console do not include the actual error when building ARB. Therefore, we need the following additional information:

- which macOS version are you using?
- please attach the full build log file (`~/Library/Logs/Homebrew/arb/01.make`)
- what is the output of `brew doctor`.

**Comment by pranalideore1** [comment]
**MacOS** - 12.1 Mac OS Monterey 

[01.make.txt](https://github.com/arb-project/homebrew-arb/files/7887678/01.make.txt)

**Brew doctor output** - 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

**Comment by jgerken** [comment]
Thank you for the details. It seems like it is a general problem when building ARB on macOS 12. I don't have access to a macOS 12 computer / VM yet to debug the problem. Therefore, it will take some to time to fix it, unfortunately.

**Comment by pranalideore1** [comment]
Thanks for your reply. Appreciate your help. I await you response whenever you happen to debug this given the limitation around accessing VM/MacOS 12.

**Comment by epruesse** [comment]
Both arb and arb@7 fail with `Undefined subroutine &ARB::prepare_to_die called`:

```
make[5]: `blib/arch/auto/ARB/ARB.bundle' is up to date.
cp blib/arch/auto/ARB/ARB.bundle /private/tmp/arb-20220127-66932-3r5sqo/arbsrc_18733/lib/ARB.bundle
9.04user 0.71system 0:12.28elapsed 79%CPU (0avgtext+0avgdata 123164maxresident)k
0inputs+0outputs (204major+99796minor)pagefaults 0swaps
[41:05.N] ------------------------------------------------ Testing scripts in PERL_SCRIPTS
testScripts.pl syntax OK
Testing tools.pm FAILED
/private/tmp/arb-20220127-66932-3r5sqo/arbsrc_18733/lib/ARB.pm:51: Undefined subroutine &ARB::prepar
e_to_die called.
```

**Comment by epruesse** [comment]
```
Can"t load "lib//ARB.bundle" for module ARB: dlopen(lib//ARB.bundle, 0x0001): symbol not found in flat namespace "__Z22GB_calc_structure_sizeP6GBDATA"
```

**Comment by epruesse** [comment]
Also happens with an old ARB I from 2018 that I still had sitting around.

**Comment by jgerken** [comment]
@epruesse I tried with different `perl` versions from Homebrew, built them from source via Homebrew and via Perlbrew but nothing fixed the problem. Do you have any other idea than providing a switch to disable building the perl support?

**Comment by epruesse** [comment]
Yes, ditching PERL and replacing it with PYTHON. (Ralf will kill me)

**Comment by epruesse** [comment]
It's trying to load symbols that aren't there because they only get built when DEBUG=1. So something with the way the "proto.h" thingies get parsed out of the code and turned into the perl export spec.

**Comment by epruesse** [comment]
With `DEBUG=1` the build succeeds.

**Comment by epruesse** [comment]
Got it.

**Comment by epruesse** [comment]
Try adding this patch:

```
--- arbsrc_18696.orig/ARBDB/arbdb.cxx	2022-01-27 18:41:50.000000000 +0000
+++ arbsrc_18696/ARBDB/arbdb.cxx	2022-01-27 18:41:01.000000000 +0000
@@ -866,6 +866,12 @@
     }
     return size;
 }
+#else
+// all GB_xyz() calls will end up in ad_prot.h and expected to be present by
+// the Perl module. We must therefore create a stub, lest perl fail to find a symbol.
+long GB_calc_structure_size(GBDATA *gbd) {
+  return 0;
+}

 #endif
```

**Comment by jgerken** [comment]
The line numbers did not match for me, but applying the patch at the correct position fixed the problem under macOS 12. Thanks a lot! :)

 Will now test it under macOS 11 and then make Ralf aware so that it can be fixed upstream.

**Update** works under macOS 11.

**Comment by epruesse** [comment]
The issue was this:

The function `long GB_calc_structure_size(GBDATA*)` is only _defined_ if `DEBUG` is true. However, it is always _declared_ because `aisk_mkpt` extracts the synopsis from `arbdb.cxx` ignoring the preprocessor macros and places it in `ad_prot.h`. This declaration is copied into `proto.h` when the PERL bindings are generated, where `arb_proto_2_xsub` sees it and generates a protocol stub in `ARB.xs`. From there, the stub is compiled into `ARB.c`, then `ARB.o` and finally `ARB.bundle`. However, since there is no definition, the symbol is found missing by the dynamic linker when `ARB.pm` is imported, and `DynaLoader` `dlopen`s ARB.bundle to create the Perl functions.

I'm sure there are other places to handle this, or even better ones. Technically, `aisc_mpkt` should parse the preprocessor macros and pass them through into the generated header file. Or `arb_proto_2_xsub` could verify that all declared functions are also defined (symbols present).

The above patch was simply the shortest fix that didn't require interfering with the build process. It just defines a dummy function. 

It's possible that using DLLs rather than static libs would also work around the issue. I'm not sure why we are using static on OSX, actually. It works with DLLs too.

**Comment by jgerken** [comment]
The problem has been solved except for the production version for which it will be solved when its next version is released:

```
# these installations work on macOS 12, too
brew install arb-project/arb/arb --HEAD
brew install arb-project/arb/arb@7
brew install arb-project/arb/arb@7 --HEAD

# this installation does not yet work on macOS 12
brew install arb-project/arb/arb
```

The release date for the next release of the production version of ARB is not yet set. I will post to this issue once it has been released and the `arb` formula has been updated.

**Comment by jgerken** [comment]
Production version 7.1-beta_r19270 has been released. This version can be installed on macOS 12 again. Now all available ARB versions compile on macOS 12. Closing this issue.
