### ISSUE TITLE
Catalina?

### ISSUE THREAD

**Issue by bholt20** [arb-project/homebrew-arb#2]
Love this. However, once I installed it via homebrew, I cannot get it to open. Running 'brew list' indicated arb is installed (arb 6.1-beta_r18342), but when running 'arb filename.arb' i get a command not found. Is this a catalina/zsh issue? 

Also tried uninstalling, removing ghostscript, and reinstalling with no luck. I have also tried downloading arb package and installing without brew, unsuccessfully.

**Comment by jgerken** [comment]
I have not yet upgraded any of my Macs to Catalina, therefore, I cannot test it directly at the moment. I can try to setup a VM with Catalina later, but for me it looks like a path issue. Could you please check if the following files exist on you Mac after installing arb?

- `/usr/local/bin/arb`
- `/usr/local/Cellar/arb/6.1-beta_r18342/bin/arb`

If they do exist, then it is a path issue. Could you restart your terminal application and try again? If that does not solve the issue please check if the result of

```bash
echo $PATH
```
includes `/usr/local/bin`.

I have no experience with `zsh` yet, so I am not sure were the path variable is set. I set mine for BASH in `~/.profile`.

**Comment by bholt20** [comment]
<img width="569" alt="Screen Shot 2020-03-17 at 11 41 11 AM" src="https://user-images.githubusercontent.com/53009624/76873631-603e9380-6844-11ea-8707-2cbb648a4cf8.png">

Thanks for the quick response! 

the usr/local/bin didn't contain arb, but the cellar did. After linking brew to the /usr/local/bin folder, i was able to open arb, but got the attached error. is this something with my ~/.profile?

**Comment by jgerken** [comment]
I have seen that problem only when I used arb remotely via `ssh` and forgot the `-X` or `-Y` option to forward the X11 connection. But that can't be the case here.

It still looks like some kind of X11 error. Do you have XQuartz installed? If yes, close the XQuartz application and try again. If that does not help, you could try rebooting the MacBook just to make sure that all system process are in a good state. You can also try to re-install XQuartz

```bash
brew cask uninstall xquartz
brew cask install xquartz
``` 

If XQuartz is not installed please install it using

```bash
brew cask install xquartz
```

**Comment by bholt20** [comment]
Uninstalling xquartz and reinstalling, following by computer restart solved everything!

Thanks for your help!

**Comment by jgerken** [comment]
You are welcome!
