### ISSUE TITLE
Perl 5.36 deprecated by Homebrew

### ISSUE THREAD

**Issue by lschreib** [arb-project/homebrew-arb#27]
I tried to install ARB using the supplied Homebrew formula, but it failed because Homebrew deprecated Perl version 5.36. It would be great if you could update everything to the Perl version 5.38 currently supported by Homebrew. Thanks.

**Comment by jgerken** [comment]
Thanks for letting us know. I'll update the formula later this week. Unfortunately, this issue will likely pop up again with version 5.38, too. ARB needs the run-time perl version to be identical to the perl version used at compile-time but Homebrew does not provide a stable perl version like it did with perl 5.18 for years. I need to think a bit about the best solution.

**Comment by lschreib** [comment]
Yes, I saw that they keep changing the supported Perl version in Homebrew. Really not an ideal scenario. Maybe running ARB as a container would solve this? On the other hand, maybe the interaction between ARB and XQuartz would be a bit tricky to work out when using containers?

**Comment by Hsuthinzarmaung** [comment]
Hi, similar issue here. Perl 5.18 also found deprecated.

**Comment by jgerken** [comment]
When I tried to fix the issue over the weekend, I stumbled into multiple issue:

- the ARB perl mapping is broken when perl is newer than perl 5.36 (no clue yet why)
- Apple has broken the linker in its Xcode Command Line Tools 15+
  - not only ARB is affected but also other programs
  - the linker complains about unsupported flags at runtime which its own `manpage` lists as supported 🤪

It would be nice if Apple fixes the issue but, fortunately, the flag is only causing a duplication check which is not too important for the ARB build. Thus, I could add a patch to the formula and we wait what Apple will do and then either add the fix permanently to the ARB source code or remove it from the formula. But that does not solve the `perl` problem.

If you are still using Commandline Tools version 14, you can use this ugly workaround to install ARB

```bash
brew tap homebrew/core
brew extract --version=5.36 perl arb-project/arb
brew install perl@5.36
brew install arb-project/arb/arb
```

Steps one and three will take some time. Have some tea or coffee ready 😉 

To figure out which version of the Commandline Tools you use:

```bash
clang --version
```

If it contains a line similar to

```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

Then you are using Commandline Tools version 14. If the version starts with 15 than you already upgrade to 15.

**Comment by marmi** [comment]
Same issue with perl@5.36. 
Appreciate the efforts by jgerken, Unfortunately no workaround possible in my case since CLT is 15.0 in a new M2 mac.
Time to wait and keep using the old machine.

**Comment by Hsuthinzarmaung** [comment]
Thanks for the workaround but sadly, mine also 15.0 so last step just say "x86_64 architecture is required for this software”. Guess nothing to do but wait.
