### ISSUE TITLE
Hi,  I get the following error during installation of arb

### ISSUE THREAD

**Issue by waakanni** [arb-project/homebrew-arb#6]
Hi,

I get the following error during installation of arb.

```
Last 15 lines from /Users/akanni/Library/Logs/Homebrew/gv/02.make:
./paths.h:38:22: note: expanded from macro 'INC_X11'
#define INC_X11(aaa) <X11/aaa>
                     ^~~~~~~~~
<scratch space>:86:1: note: expanded from here
<X11/Xlib.h>
^~~~~~~~~~~~
make[2]: *** [Aaa_lex.o] Error 1
make[2]: *** [Aaa_bison.o] Error 1
make[2]: *** [Aaa.o] Error 1
1 error generated.
make[2]: *** [Ghostview.o] Error 1
1 error generated.
make[2]: *** [FileSel.o] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```
There is also a warning:
```
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the denismm/gv tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/denismm/homebrew-gv/Formula/gv.rb:10
```

**Comment by jgerken** [comment]
The error you report is in the formula `denims/gv` on which we depend. We can't fix the problem in the dependency. On which macOS version do you use?

However, the Homebrew maintainers by now have introduced the breaking change to remove the `:x11` dependency completely. Therefore, I can't build ARB at all even though I have the `gv` dependency already installed. Unfortunately, it seems like it will take some time to fix. Therefore, I can't promise any time at which the formula will be working again. Sorry!

**Comment by jgerken** [comment]
Just a short progress report:

- I managed to make ARB compile on macOS again
- the dependency on the `gv` formula was removed for macOS by the ARB maintainer
- the dedicated `arb-project/arb/xfig` formula could be replace with the default `xfig` formula from Homebrew
- unfortunately parts of the application crash under macOS while working fine on Linux

I hope to find a solution to the crashes next week. I'll let you know when a fix is available.

**Comment by jgerken** [comment]
Sorry for the long time it took to fix the issue but finally the formula works again :)

**Comment by waakanni** [comment]
Awesome. Thank you
