### ISSUE TITLE
arb x11 and xfig install issue on Big Sur

### ISSUE THREAD

**Issue by HollyKArnold** [arb-project/homebrew-arb#7]
Hello,

I'm hoping to install ARB on macOS Big Sur 11.2.3. Unfortunately, I get the following errors when trying to install. Any ideas on how to fix the issue?

```
brew tap arb-project/arb
==> Tapping arb-project/arb
Cloning into '/usr/local/Homebrew/Library/Taps/arb-project/homebrew-arb'...
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (182/182), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 194 (delta 77), reused 127 (delta 42), pack-reused 12
Receiving objects: 100% (194/194), 47.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (79/79), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/arb-project/homebrew-arb/Formula/arb.rb
arb: Unsupported special dependency :x11
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/arb-project/homebrew-arb/Formula/xfig.rb
xfig: Unsupported special dependency :x11
Error: Cannot tap arb-project/arb: invalid syntax in tap!
```

And then I get the following when trying to install x-quartz

```
brew cask install xquartz
Error: Unknown command: cask
```

which can be fixed by:

```
brew install --cask xquartz
```

And quartz has installed successfully. 

But then when running the next command, I get the following

```
brew tap denismm/gv
==> Tapping denismm/gv
Cloning into '/usr/local/Homebrew/Library/Taps/denismm/homebrew-gv'...
remote: Enumerating objects: 28, done.
remote: Total 28 (delta 0), reused 0 (delta 0), pack-reused 28
Unpacking objects: 100% (28/28), done.
Checking connectivity... done.
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the denismm/gv tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/denismm/homebrew-gv/Formula/ghostscript.rb:9

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the denismm/gv tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/denismm/homebrew-gv/Formula/ghostscript.rb:10

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the denismm/gv tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/denismm/homebrew-gv/Formula/ghostscript.rb:11

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/denismm/homebrew-gv/Formula/ghostscript.rb
ghostscript: Unsupported special dependency :x11
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/denismm/homebrew-gv/Formula/gv.rb
gv: Unsupported special dependency :x11
Error: Cannot tap denismm/gv: invalid syntax in tap!
```

Any ideas on how to fix the problem? Any insight would be especially appreciated.

**Comment by jgerken** [comment]
Hi,

regarding the XQuartz installation issue, I forgot to update the documentation to the changed syntax in Homebrew.

The most difficult problem to solve is the dependency on `:x11`. Homebrew suddenly removed support for it in a minor update and I could not find a solution around it yet. It seems that the stuff Homebrew does in it recent version is incompatible with the way ARB is build. In theory, the dependency to `:x11` should just be replaced with dependencies to specific X11 libraries but that did not work, Homebrew made the dependencies available in a different than the ARB build file is expecting them. Unfortunately, I do not have any idea what you could try right now. The issue with the `gv` formula is cause by the same problem. So if we can solve it for ARB we should be able to solve it for `gv`, too.
 
I‘ll try to find time next week to have a look if the situation changed and I can make the formula work again. I hope to be able to provide at least a workaround via Docker if I can’t make the formula work again.

**Comment by jgerken** [comment]
Just a short progress report:

- I managed to make ARB compile on macOS again
- the dependency on the `gv` formula was removed for macOS by the ARB maintainer
- the dedicated `arb-project/arb/xfig` formula could be replace with the default `xfig` formula from Homebrew
- unfortunately parts of the application crash under macOS while working fine on Linux

I hope to find a solution to the crashes next week. I'll let you know when a fix is available.

**Comment by jgerken** [comment]
Sorry for the long time it took to fix the issue but finally the formula works again :)
